AWSTemplateFormatVersion: '2010-09-09'
Description: 'The template used to create an ECS Cluster & CodeDeploy Application.'

Parameters:
  ECSClusterName:
    Type: String
    Default: foo-server-cluster

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Ref ECSClusterName

  Application:
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: !Sub '${AWS::StackName}-app'
      ComputePlatform: ECS
